### ISSUE TITLE
Getting it running under windows

### ISSUE THREAD

**Issue by tipih** [ndesai/qml-qmqtt#1]
Hi.
I have problem in getting it to run under windows, works fine under Linux and MAC OS

But on windows I get Linker errors. 

Here is a small path of the error BTW. using Qt 5.4 32bit mingw compiler
g++ -Wl,-subsystem,windows -mthreads -o debug\mqtt.exe object_script.mqtt.Debug  -lglu32 -lopengl32 -lgdi32 -luser32 -lmingw32 -LC:/Qt/5.4/mingw491_32/lib -lqtmaind -LC:\mingw491\mingw32\lib -LC:\Utils\icu32_53_1_mingw482\lib -LC:\utils\postgresql\pgsql\lib -LC:\utils\mysql\mysql\lib -LC:\opensll\lib -lshell32 -LC:\Qt\5.4\mingw491_32/lib -lQt5Quickd -lQt5Guid -lQt5Qmld -lQt5Networkd -lQt5Cored 
./debug\qmqtt_client.o: In function `ZN5QMQTT6ClientC2ERK7QStringjP7QObject':
C:\Users\$hschack\Documents\qml-qmqtt/qmqtt_client.cpp:39: undefined reference to`_imp___ZTVN5QMQTT6ClientE'
./debug\qmqtt_client.o: In function `ZN5QMQTT6ClientD2Ev':
C:\Users\$hschack\Documents\qml-qmqtt/qmqtt_client.cpp:44: undefined reference to`_imp___ZTVN5QMQTT6ClientE'
./debug\qmqtt_client.o: In function `ZN5QMQTT6Client11onConnectedEv':
C:\Users\$hschack\Documents\qml-qmqtt/qmqtt_client.cpp:166: undefined reference to`_imp___ZN5QMQTT6Client9connectedEv'
./debug\qmqtt_client.o: In function `ZN5QMQTT6Client7publishERNS_7MessageE':
C:\Users\$hschack\Documents\qml-qmqtt/qmqtt_client.cpp:172: undefined reference to`_imp___ZN5QMQTT6Client9publishedERNS_7MessageE'
./debug\qmqtt_client.o: In function `ZN5QMQTT6Client6pubackEht':
C:\Users\$hschack\Documents\qml-qmqtt/qmqtt_client.cpp:179: undefined reference to`_imp___ZN5QMQTT6Client8pubackedEht'
./debug\qmqtt_client.o: In function `ZN5QMQTT6Client9subscribeERK7QStringh':
C:\Users\$hschack\Documents\qml-qmqtt/qmqtt_client.cpp:185: undefined reference to`_imp___ZN5QMQTT6Client10subscribedERK7QString'
./debug\qmqtt_client.o: In function `ZN5QMQTT6Client11unsubscribeERK7QString':
C:\Users\$hschack\Documents\qml-qmqtt/qmqtt_client.cpp:192: undefined reference to`_imp___ZN5QMQTT6Client12unsubscribedERK7QString'
./debug\qmqtt_client.o: In function `ZN5QMQTT6Client14onDisconnectedEv':
C:\Users\$hschack\Documents\qml-qmqtt/qmqtt_client.cpp:208: undefined reference to`_imp___ZN5QMQTT6Client12disconnectedEv'
./debug\qmqtt_client.o: In function `ZN5QMQTT6Client10onReceivedERNS_5FrameE':
C:\Users\$hschack\Documents\qml-qmqtt/qmqtt_client.cpp:256: undefined reference to`_imp___ZN5QMQTT6Client8subackedEth'
C:\Users\$hschack\Documents\qml-qmqtt/qmqtt_client.cpp:259: undefined reference to `_imp___ZN5QMQTT6Client10unsubackedEt'
C:\Users\$hschack\Documents\qml-qmqtt/qmqtt_client.cpp:262: undefined reference to`_imp___ZN5QMQTT6Client4pongEv'
./debug\qmqtt_client.o: In function `ZN5QMQTT6Client13handleConnackEh':
C:\Users\$hschack\Documents\qml-qmqtt/qmqtt_client.cpp:272: undefined reference to`_imp___ZN5QMQTT6Client9connackedEh'
./debug\qmqtt_client.o: In function `ZN5QMQTT6Client13handlePublishERNS_7MessageE':
C:\Users\$hschack\Documents\qml-qmqtt/qmqtt_client.cpp:282: undefined reference to`_imp___ZN5QMQTT6Client8receivedERKNS_7MessageE'
./debug\qmqtt_client.o: In function `ZN5QMQTT6Client12handlePubackEht':
C:\Users\$hschack\Documents\qml-qmqtt/qmqtt_client.cpp:292: undefined reference to`_imp___ZN5QMQTT6Client8pubackedEht'
./debug\mqtt.o: In function `ZN4MQTT20initializeConnectionEv':
C:\Users\$hschack\Documents\qml-qmqtt/mqtt.cpp:24: undefined reference to`_imp___ZN5QMQTT6ClientC1ERK7QStringjP7QObject'
C:\Users\$hschack\Documents\qml-qmqtt/mqtt.cpp:25: undefined reference to `_imp___ZN5QMQTT6Client11setClientIdERK7QString'
C:\Users\$hschack\Documents\qml-qmqtt/mqtt.cpp:28: undefined reference to`_imp___ZN5QMQTT6Client7connectEv'
./debug\mqtt.o: In function `ZN4MQTT10disconnectEv':
C:\Users\$hschack\Documents\qml-qmqtt/mqtt.h:159: undefined reference to`_imp___ZN5QMQTT6Client10disconnectEv'
./debug\moc_qmqtt_client.o: In function `ZN5QMQTT6Client18qt_static_metacallEP7QObjectN11QMetaObject4CallEiPPv':
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:197: undefined reference to`_imp___ZN5QMQTT6Client7connectEv'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:198: undefined reference to `_imp___ZN5QMQTT6Client7publishERNS_7MessageE'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:200: undefined reference to`_imp___ZN5QMQTT6Client6pubackEht'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:201: undefined reference to `_imp___ZN5QMQTT6Client9subscribeERK7QStringh'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:203: undefined reference to`_imp___ZN5QMQTT6Client11unsubscribeERK7QString'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:204: undefined reference to `_imp___ZN5QMQTT6Client4pingEv'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:205: undefined reference to`_imp___ZN5QMQTT6Client10disconnectEv'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:206: undefined reference to `_imp___ZN5QMQTT6Client11onConnectedEv'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:207: undefined reference to`_imp___ZN5QMQTT6Client14onDisconnectedEv'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:208: undefined reference to `_imp___ZN5QMQTT6Client10onReceivedERNS_5FrameE'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:209: undefined reference to`_imp___ZN5QMQTT6Client13handlePublishERNS_7MessageE'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:210: undefined reference to `_imp___ZN5QMQTT6Client13handleConnackEh'

**Comment by ndesai** [comment]
Sorry, I don't use Windows. 
I can help if you switch to a real operating system :)

**Comment by tipih** [comment]
I manage to fix the code, there was some general compiler errors, releated to creating a lib or a dll and then use it.

**Comment by afigar** [comment]
Please, @tipih, could you be more specific? how did you solve this?
